name: rss news feed build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: make install

      - name: build
        run: make build

      - name: lint
        run: make lint
